version: '3.2'
services:
  microservice-collector-manufacturers:
    image: manufacturers/node:1.0
    container_name: microservice-collector-date-reference
    environment:
      - SQS_URL_DATE=http://localstack:4566/000000000000/data-reference-queue
      - SQS_URL_MANUFACTURERS=http://localstack:4566/000000000000/manufacturers-queue
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_KEY=123
      - MONGO_URL=mongodb://mongodb:27017/vehicles
      - REGION=us-east-1
      - PORT=5000
    ports:
      - 5000:5000
    restart: unless-stopped
networks:
  default:
    external:
      name: networking-microservices